local T, C, L = unpack(Tukui)

local kuihelp = CreateFrame("Button", "KacaosUIHelpFrame", UIParent)
kuihelp:SetSize(490, 560)
kuihelp:SetPoint("CENTER")
kuihelp:SetTemplate("Transparent")
kuihelp:CreateShadow("Default")
kuihelp:SetFrameStrata("HIGH")
kuihelp:FontString("Text", C.media.font, 13)
kuihelp.Text:SetPoint("TOPLEFT", 9, -20)
kuihelp.Text:SetText(L.kui_help3..L.kui_help4..L.kui_help5..L.kui_help5a..L.kui_help6..L.kui_help7..L.kui_help8..L.kui_help9..L.kui_help10..L.kui_help10aa..L.kui_help10a..L.kui_help10b..L.kui_help10c..	L.kui_help10d..L.kui_help11..L.kui_help12..L.kui_help13..L.kui_help14..L.kui_help15..L.kui_help16..L.kui_help17..L.kui_help18..L.kui_help18a..L.kui_help18b..L.kui_help19..L.kui_help20..L.kui_help21..L.kui_help22..L.kui_help22a..L.kui_help23)
kuihelp:Hide()
kuihelp:SetMovable(true)
kuihelp:SetScript("OnMouseDown", function() kuihelp:ClearAllPoints() kuihelp:StartMoving() end)
kuihelp:SetScript("OnMouseUp", function() kuihelp:StopMovingOrSizing() end)

local kuihelp_logo = CreateFrame("Button", "KacaosUILogo", KacaosUIHelpFrame)
kuihelp_logo:SetSize(70, 38)
kuihelp_logo:SetPoint("TOPLEFT", KacaosUIHelpFrame, "TOPLEFT", 55, 42)
kuihelp_logo:SetTemplate("Transparent")
kuihelp_logo:CreateShadow("Default")
kuihelp_logo:SetFrameLevel(KacaosUIHelpFrame:GetFrameLevel() + 1)
kuihelp_logo:FontString("Text", C.media.font, 16)
kuihelp_logo.Text:SetPoint("CENTER")
kuihelp_logo.Text:SetText(L.kui_help1..L.kui_help1b)

local kuihelp_pic = CreateFrame("Button", "KacaosUIPic", KacaosUIHelpFrame)
kuihelp_pic:SetSize(80, 70)
kuihelp_pic:SetPoint("TOPLEFT", KacaosUIHelpFrame, "TOPLEFT", -30, 42)
kuihelp_pic:SetTemplate("Default")
kuihelp_pic:CreateShadow("Default")
kuihelp_pic:SetFrameLevel(KacaosUIHelpFrame:GetFrameLevel() + 1)

local kuihelp_pic_tex = kuihelp_pic:CreateTexture(nil, "OVERLAY")
kuihelp_pic_tex:SetTexture(C.media.kuihelp_pic)
kuihelp_pic_tex:SetPoint("TOPLEFT", kuihelp_pic, "TOPLEFT", 2, -2)
kuihelp_pic_tex:SetPoint("BOTTOMRIGHT", kuihelp_pic, "BOTTOMRIGHT", -2, 2)

local kuihelp_info = CreateFrame("Button", "KacaosUIInfo", KacaosUIHelpFrame)
kuihelp_info:SetSize(300, 30)
kuihelp_info:SetPoint("CENTER", KacaosUIHelpFrame, "TOP", 0, -24)
kuihelp_info:SetBackdropColor(0,0,0,0)
kuihelp_info:SetBackdropBorderColor(0,0,0,0)
kuihelp_info:SetFrameLevel(KacaosUIHelpFrame:GetFrameLevel() + 1)
kuihelp_info:FontString("Text", C.media.font, 15)
kuihelp_info.Text:SetPoint("CENTER")
kuihelp_info.Text:SetText(L.kui_help2)

local kuihelp_close = CreateFrame("Button", "KacaosUIFrameClose", KacaosUIHelpFrame)
kuihelp_close:SetSize(15, 15)
kuihelp_close:SetPoint("TOPRIGHT", KacaosUIHelpFrame, "TOPRIGHT", -2, -2)
kuihelp_close:SetBackdropColor(0,0,0,0)
kuihelp_close:SetBackdropBorderColor(0,0,0,0)
kuihelp_close:SetFrameLevel(KacaosUIHelpFrame:GetFrameLevel() + 1)
kuihelp_close:FontString("Text", C.media.pixelfont, 14)
kuihelp_close.Text:SetPoint("CENTER")
kuihelp_close.Text:SetText("x")
kuihelp_close:SetScript("OnClick", function()
	kuihelp:Hide()
end)

SLASH_KUIHELP1 = "/kuihelp"
SlashCmdList.KUIHELP = function() if kuihelp:IsShown() then kuihelp:Hide() else kuihelp:Show() end end